#!/usr/bin/env bash
# inject-firstrun.sh — Inject pi-setup steps into a freshly-flashed RPi boot partition.
# Run on your Mac/Linux/WSL machine after flashing with Raspberry Pi Imager, before first boot.
# The FAT32 boot partition auto-mounts and is writable — no special tools needed.
#
# Usage:
#   ./inject-firstrun.sh <boot-path> [options]
#
# Examples:
#   macOS : ./inject-firstrun.sh /Volumes/bootfs  --nas-host 192.168.1.10
#   Linux : ./inject-firstrun.sh /media/$USER/bootfs --nas-host 192.168.1.10
#   WSL   : ./inject-firstrun.sh /mnt/e  --nas-host 192.168.1.10
#
# Options:
#   --nas-host HOST       NAS hostname or IP
#   --nas-share NAME      Share name (default: grifData)
#   --nas-user USER       CIFS username
#   --nas-password PASS   CIFS password
#   --nas-creds FILE      Path to existing credentials file (embedded into the image)
#   --docker-user USER    User to add to docker group (default: beartums)
#   --skip-nas            Skip NAS setup
#   --skip-docker         Skip Docker setup
#   --legacy-boot         Target /boot instead of /boot/firmware (Bullseye and older)

set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'
info() { echo -e "${CYAN}[INFO]${RESET}  $*"; }
ok()   { echo -e "${GREEN}[ OK ]${RESET}  $*"; }
warn() { echo -e "${YELLOW}[WARN]${RESET}  $*"; }
die()  { echo -e "${RED}[ERR]${RESET}   $*" >&2; exit 1; }

# ─── Args ─────────────────────────────────────────────────────────────────────

BOOT_PATH=""
NAS_HOST=""
NAS_SHARE="grifData"
NAS_USER=""
NAS_PASSWORD=""
NAS_CREDS_FILE=""
DOCKER_USER="beartums"
SKIP_NAS=false
SKIP_DOCKER=false
LEGACY_BOOT=false

# First positional arg is the boot partition path
[[ $# -gt 0 && "${1:0:2}" != "--" ]] && { BOOT_PATH="$1"; shift; }

while [[ $# -gt 0 ]]; do
  case "$1" in
    --nas-host)     NAS_HOST="$2";       shift 2 ;;
    --nas-share)    NAS_SHARE="$2";      shift 2 ;;
    --nas-user)     NAS_USER="$2";       shift 2 ;;
    --nas-password) NAS_PASSWORD="$2";   shift 2 ;;
    --nas-creds)    NAS_CREDS_FILE="$2"; shift 2 ;;
    --docker-user)  DOCKER_USER="$2";    shift 2 ;;
    --skip-nas)     SKIP_NAS=true;       shift ;;
    --skip-docker)  SKIP_DOCKER=true;    shift ;;
    --legacy-boot)  LEGACY_BOOT=true;    shift ;;
    *) die "Unknown option: $1" ;;
  esac
done

# ─── Validate ─────────────────────────────────────────────────────────────────

[[ -n "$BOOT_PATH" ]]          || die "Boot partition path required as first argument"
[[ -d "$BOOT_PATH" ]]          || die "Not a directory: $BOOT_PATH"
[[ -f "$BOOT_PATH/cmdline.txt" ]] \
  || die "cmdline.txt not found in $BOOT_PATH — is this the right partition?"

if [[ "$LEGACY_BOOT" == "true" ]]; then
  PI_BOOT=/boot
else
  PI_BOOT=/boot/firmware
  # Auto-detect legacy: if the volume name is just "boot" it's likely Bullseye
  VOL_NAME=$(basename "$BOOT_PATH")
  if [[ "$VOL_NAME" == "boot" ]]; then
    warn "Volume is named 'boot' — looks like Bullseye. Using /boot (pass --legacy-boot to suppress this warning)"
    PI_BOOT=/boot
  fi
fi
info "Pi-side boot path: $PI_BOOT"

# ─── Credentials ──────────────────────────────────────────────────────────────

if [[ "$SKIP_NAS" == "false" ]]; then
  [[ -n "$NAS_HOST" ]] || die "--nas-host is required for NAS setup (or pass --skip-nas)"

  CREDS_CONTENT=""

  if [[ -n "$NAS_CREDS_FILE" ]]; then
    [[ -f "$NAS_CREDS_FILE" ]] || die "Credentials file not found: $NAS_CREDS_FILE"
    CREDS_CONTENT=$(cat "$NAS_CREDS_FILE")
    ok "Using credentials file: $NAS_CREDS_FILE"
  elif [[ -n "$NAS_USER" ]]; then
    if [[ -z "$NAS_PASSWORD" ]]; then
      read -rsp "$(echo -e "${YELLOW}NAS password for ${NAS_USER}:${RESET} ")" NAS_PASSWORD
      echo
    fi
    CREDS_CONTENT="username=${NAS_USER}
password=${NAS_PASSWORD}"
  else
    info "No credentials provided — prompting interactively"
    read -rp  "$(echo -e "${YELLOW}NAS username:${RESET} ")" NAS_USER
    read -rsp "$(echo -e "${YELLOW}NAS password:${RESET} ")" NAS_PASSWORD
    echo
    CREDS_CONTENT="username=${NAS_USER}
password=${NAS_PASSWORD}"
  fi

  # Write credentials to the boot partition so firstrun.sh can move them
  # (avoids embedding the password directly in the script text)
  printf '%s\n' "$CREDS_CONTENT" > "$BOOT_PATH/cifs-credentials"
  ok "Credentials staged on boot partition (will be moved to /etc on first boot)"
  warn "Note: credentials are readable by anyone with SD card access until first boot"
fi

# ─── Generate firstrun.sh ─────────────────────────────────────────────────────

FIRSTRUN="$BOOT_PATH/pi-setup-firstrun.sh"

cat > "$FIRSTRUN" <<SCRIPT
#!/bin/bash
# pi-setup-firstrun.sh — runs once on first Pi boot, then self-removes.
# Generated by inject-firstrun.sh on $(date -Iseconds 2>/dev/null || date)
set -euo pipefail
exec >> /var/log/pi-setup-firstrun.log 2>&1
echo "[$(date -Iseconds)] ── pi-setup-firstrun.sh starting ──"

BOOT_PT="${PI_BOOT}"

# Wait for apt to be available (cloud-init or other first-boot tasks may hold the lock)
for i in \$(seq 1 30); do
  flock -w 1 /var/lib/dpkg/lock-frontend true 2>/dev/null && break
  echo "Waiting for apt lock... (\$i/30)"
  sleep 5
done

apt-get update -y -qq

$(if [[ "$SKIP_NAS" == "false" ]]; then cat <<'NAS_BLOCK'
# ── NAS / CIFS ──────────────────────────────────────────────────────────────
echo "[$(date -Iseconds)] Installing cifs-utils..."
apt-get install -y cifs-utils

# Move staged credentials off the FAT partition into /etc
if [ -f "${BOOT_PT}/cifs-credentials" ]; then
  mv "${BOOT_PT}/cifs-credentials" /etc/cifs-credentials
  chmod 600 /etc/cifs-credentials
  echo "[$(date -Iseconds)] Credentials moved to /etc/cifs-credentials"
fi

NAS_BLOCK
fi)
NAS_HOST_VAL="${NAS_HOST}"
NAS_SHARE_VAL="${NAS_SHARE}"
MOUNT_POINT="/mnt/${NAS_SHARE}"

$(if [[ "$SKIP_NAS" == "false" ]]; then cat <<'NAS_BLOCK2'
UNC="//${NAS_HOST_VAL}/${NAS_SHARE_VAL}"
mkdir -p "${MOUNT_POINT}"

FSTAB_LINE="${UNC}  ${MOUNT_POINT}  cifs  credentials=/etc/cifs-credentials,iocharset=utf8,vers=3.0,_netdev,nofail  0  0"
if ! grep -qF "${MOUNT_POINT}" /etc/fstab; then
  echo "" >> /etc/fstab
  echo "# pi-setup: ${MOUNT_POINT}" >> /etc/fstab
  echo "${FSTAB_LINE}" >> /etc/fstab
  echo "[$(date -Iseconds)] fstab entry added for ${UNC}"
fi

mount "${MOUNT_POINT}" 2>/dev/null \
  && echo "[$(date -Iseconds)] Mounted ${UNC} → ${MOUNT_POINT}" \
  || echo "[$(date -Iseconds)] WARNING: mount failed — check NAS availability and credentials"
NAS_BLOCK2
fi)

$(if [[ "$SKIP_DOCKER" == "false" ]]; then cat <<'DOCKER_BLOCK'
# ── Docker ───────────────────────────────────────────────────────────────────
echo "[$(date -Iseconds)] Installing Docker..."
curl -fsSL https://get.docker.com | sh

if docker compose version &>/dev/null 2>&1; then
  echo "[$(date -Iseconds)] Docker Compose plugin present"
else
  apt-get install -y docker-compose-plugin
fi
DOCKER_BLOCK
fi)
DOCKER_USER_VAL="${DOCKER_USER}"
$(if [[ "$SKIP_DOCKER" == "false" ]]; then cat <<'DOCKER_USER_BLOCK'
if id "${DOCKER_USER_VAL}" &>/dev/null; then
  usermod -aG docker "${DOCKER_USER_VAL}"
  echo "[$(date -Iseconds)] ${DOCKER_USER_VAL} added to docker group"
else
  echo "[$(date -Iseconds)] WARNING: user '${DOCKER_USER_VAL}' not found — skipping docker group"
fi
DOCKER_USER_BLOCK
fi)

# ── Cleanup: remove this script and its systemd.run entry ────────────────────
echo "[$(date -Iseconds)] ── pi-setup-firstrun.sh complete — cleaning up ──"
rm -f "${BOOT_PT}/pi-setup-firstrun.sh"
sed -i "s| systemd\.run[^ ]*||g" "${BOOT_PT}/cmdline.txt"
SCRIPT

chmod +x "$FIRSTRUN"
ok "firstrun script written: $FIRSTRUN"

# ─── Modify cmdline.txt ───────────────────────────────────────────────────────

CMDLINE_FILE="$BOOT_PATH/cmdline.txt"
CMDLINE=$(cat "$CMDLINE_FILE")

SYSTEMD_RUN="systemd.run=${PI_BOOT}/pi-setup-firstrun.sh"

if echo "$CMDLINE" | grep -q "pi-setup-firstrun"; then
  warn "cmdline.txt already has a pi-setup-firstrun entry — skipping modification"
else
  # Append to the single-line cmdline — must remain one line
  printf '%s %s\n' "${CMDLINE%$'\n'}" "$SYSTEMD_RUN" > "$CMDLINE_FILE"
  ok "cmdline.txt updated"
fi

# ─── Summary ─────────────────────────────────────────────────────────────────

echo
echo -e "${GREEN}${BOLD}╔══════════════════════════════════════════════════════╗${RESET}"
echo -e "${GREEN}${BOLD}║  Boot partition ready                                ║${RESET}"
echo -e "${GREEN}${BOLD}╚══════════════════════════════════════════════════════╝${RESET}"
echo
info "Partition : $BOOT_PATH"
[[ "$SKIP_NAS"    == "false" ]] && info "NAS       : //${NAS_HOST}/${NAS_SHARE} → /mnt/${NAS_SHARE}"
[[ "$SKIP_DOCKER" == "false" ]] && info "Docker    : will be installed for user '${DOCKER_USER}'"
info "Log       : /var/log/pi-setup-firstrun.log (on the Pi after first boot)"
echo
warn "Eject the SD card safely before inserting it into the Pi"
